version: '3'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    # ports:
    #   - "80:80"
    tty: true
    networks: 
      - node-network
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  nginx:
    depends_on:
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3063:80"
      # - "443:443"
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge